# Adopted from https://github.com/Pocket/pocket-monorepo/tree/main/.circleci
jobs:
  lint:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      # TODO: can we make this a pre-build step?
      - generate_prisma_client
      - run:
          name: Lint
          # Need to build first, so the linter picks up all needed imports
          command: |
            pnpm run build
            pnpm run lint

  # checks for mismatched npm package versions
  mismatched_versions:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Check for Mismatch
          command: |
            pnpm list-mismatches

  test:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      - generate_prisma_client
      - run:
          name: Test
          command: |
            pnpm run test

workflows:
  monorepo:
    jobs:
      - lint:
          <<: *not_dev_main
          context: pocket
      - test:
          <<: *not_dev_main
          context: pocket
      - mismatched_versions:
          <<: *not_dev_main
          context: pocket