-- Remove the UUID default from Section.externalId.
-- ML-generated Sections provide their own externalId, and Custom Sections
-- now use a human-readable slug generated from the section title.
ALTER TABLE `Section` ALTER COLUMN `externalId` DROP DEFAULT;

-- Migrate custom section externalIds from UUIDs to title-based slugs.
-- Slugs generated by a temporary script using the same titleToSlug() function.

UPDATE `Section` SET `externalId` = 'breaking-news' WHERE `externalId` = '41198075-f7ca-47a4-bc0b-828085796a24';
UPDATE `Section` SET `externalId` = 'breaking-news-2' WHERE `externalId` = '24073b6b-f515-4396-a0d6-c038312dadf4';
UPDATE `Section` SET `externalId` = 'bright-spots' WHERE `externalId` = '4eee57db-bd8a-442e-8a49-35ccf0b65536';
UPDATE `Section` SET `externalId` = 'by-the-numbers' WHERE `externalId` = '1cadf07e-0b63-4087-869b-d063fd5e0940';
UPDATE `Section` SET `externalId` = 'connections' WHERE `externalId` = '2bce2d9b-2925-4325-9f64-d42bfd1cc116';
UPDATE `Section` SET `externalId` = 'downtime' WHERE `externalId` = '310750f9-8bc9-42f5-8814-f2332f507260';
UPDATE `Section` SET `externalId` = 'explained' WHERE `externalId` = 'eeaeb30c-c26a-4ead-b6b2-157b286e30ac';
UPDATE `Section` SET `externalId` = 'featured-videos' WHERE `externalId` = '2844351f-3e3b-4bcf-a391-10247d9376a6';
UPDATE `Section` SET `externalId` = 'for-your-weekend' WHERE `externalId` = 'db63ce38-8fe1-4178-8cee-ca6e046cee36';
UPDATE `Section` SET `externalId` = 'guide-to-gift-guides' WHERE `externalId` = 'f91013e9-6143-4947-ae78-2896d91a2810';
UPDATE `Section` SET `externalId` = 'highly-specific' WHERE `externalId` = '55a2beba-aaa6-457e-aae6-6f5303f13c2f';
UPDATE `Section` SET `externalId` = 'holiday-help' WHERE `externalId` = '5c4d7e9a-95c9-4d71-932f-4dc4fd958404';
UPDATE `Section` SET `externalId` = 'ice-clashes-what-to-know' WHERE `externalId` = '2a20d32c-2a31-4bc2-9b80-1fc161a2449c';
UPDATE `Section` SET `externalId` = 'in-conversation' WHERE `externalId` = '8fcc26e8-2f0c-46f7-9a6c-4da0a5e2361b';
UPDATE `Section` SET `externalId` = 'in-the-zeitgeist' WHERE `externalId` = '6ce1c5fb-5c63-4f40-a0c1-6ee2fef6cd19';
UPDATE `Section` SET `externalId` = 'iran-protests-what-to-know' WHERE `externalId` = '14da2b17-ab7e-4073-a74f-1d92dca33782';
UPDATE `Section` SET `externalId` = 'long-reads' WHERE `externalId` = 'c037a6d9-2d3a-4d56-8f03-c41c9364413a';
UPDATE `Section` SET `externalId` = 'obsessionhobbiesoddities' WHERE `externalId` = '37acd621-e63c-4129-9f36-d4b5bd530323';
UPDATE `Section` SET `externalId` = 'photojournalism' WHERE `externalId` = '181749ca-e40e-44e2-9265-50a075e4d98b';
UPDATE `Section` SET `externalId` = 'quizzes-and-puzzles' WHERE `externalId` = 'd58a9b2b-de02-42fd-943b-246ed92e0767';
UPDATE `Section` SET `externalId` = 'small-wins' WHERE `externalId` = 'a016356b-80cb-4165-88c7-87119e7ce87b';
UPDATE `Section` SET `externalId` = 'super-bowl-lx' WHERE `externalId` = '64004241-b470-4b0d-8978-9142da0d92fd';
UPDATE `Section` SET `externalId` = 'tax-season' WHERE `externalId` = 'ab7583fc-dce7-4d7c-93b4-bc8ec8e40a08';
UPDATE `Section` SET `externalId` = 'thanksgiving' WHERE `externalId` = 'd4bd4757-ebfa-4b27-aab6-7734afbaa94a';
UPDATE `Section` SET `externalId` = 'venezuela-latest' WHERE `externalId` = '209996cf-aac4-4d6c-a2f5-13d40b702d89';
UPDATE `Section` SET `externalId` = 'what-is-this-thing' WHERE `externalId` = '68c4f757-01ba-41ff-ad4a-03476b9c47ac';
UPDATE `Section` SET `externalId` = 'who-knew' WHERE `externalId` = '905a69f9-af41-4a61-ae4c-a2de0492a81e';
UPDATE `Section` SET `externalId` = 'winter-olympics' WHERE `externalId` = '3e9355eb-2e7d-4e66-b26f-cf0b503c770b';
UPDATE `Section` SET `externalId` = 'work-life' WHERE `externalId` = '083235c5-ada6-43fc-b240-b8af368dcdf3';
UPDATE `Section` SET `externalId` = 'year-in-review' WHERE `externalId` = 'ec1df3f8-1946-43b2-a804-65c776bd0cb0';
