-- CreateTable
CREATE TABLE `PublisherDomain` (
    `domainName` VARCHAR(255) NOT NULL,
    `publisher` VARCHAR(255) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdBy` VARCHAR(255) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL,
    `updatedBy` VARCHAR(255) NULL,

    PRIMARY KEY (`domainName`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Insert publisher domain data
-- The domain names are sourced from domain_business_metadata,
-- and narrowed down to those that were associated with a
-- ScheduledItem or SectionItem at any point in time.
INSERT INTO `PublisherDomain` (`domainName`, `publisher`, `createdBy`, `updatedAt`)
SELECT DISTINCT
    dbm.domain_name,
    dbm.name,
    'migration',
    CURRENT_TIMESTAMP(3)
FROM (
    SELECT 'The Economist 1843' as name, '1843magazine.com' as domain_name
    UNION ALL SELECT '20 Minutes', '20minutes.fr'
    UNION ALL SELECT '9to5Google', '9to5google.com'
    UNION ALL SELECT '9to5Mac', '9to5mac.com'
    UNION ALL SELECT 'ABC', 'abc.es'
    UNION ALL SELECT 'ABC', 'abc.net.au'
    UNION ALL SELECT 'ABC News', 'abcnews.go.com'
    UNION ALL SELECT 'Adweek', 'adweek.com'
    UNION ALL SELECT 'Aeon', 'aeon.co'
    UNION ALL SELECT 'Financial Review', 'afr.com'
    UNION ALL SELECT 'Al Jazeera English', 'aljazeera.com'
    UNION ALL SELECT 'Android Authority', 'androidauthority.com'
    UNION ALL SELECT 'Android Police', 'androidpolice.com'
    UNION ALL SELECT 'Ansa', 'ansa.it'
    UNION ALL SELECT 'Apartment Therapy', 'apartmenttherapy.com'
    UNION ALL SELECT 'The Associated Press', 'apnews.com'
    UNION ALL SELECT 'AppleInsider', 'appleinsider.com'
    UNION ALL SELECT 'Applesfera', 'applesfera.com'
    UNION ALL SELECT 'ArchDaily', 'archdaily.com'
    UNION ALL SELECT 'Ars Technica', 'arstechnica.com'
    UNION ALL SELECT 'The Art of Manliness', 'artofmanliness.com'
    UNION ALL SELECT 'Atlas Obscura', 'atlasobscura.com'
    UNION ALL SELECT 'The A.V. Club', 'avclub.com'
    UNION ALL SELECT 'Axios', 'axios.com'
    UNION ALL SELECT 'Eric Barker', 'bakadesuyo.com'
    UNION ALL SELECT 'BBC', 'bbc.co.uk'
    UNION ALL SELECT 'BBC', 'bbc.com'
    UNION ALL SELECT 'BGR', 'bgr.com'
    UNION ALL SELECT 'Big Think', 'bigthink.com'
    UNION ALL SELECT 'Billboard', 'billboard.com'
    UNION ALL SELECT 'Bleacher Report', 'bleacherreport.com'
    UNION ALL SELECT 'Scientific American', 'blogs.scientificamerican.com'
    UNION ALL SELECT 'Bloomberg', 'bloomberg.com'
    UNION ALL SELECT 'Boing Boing', 'boingboing.net'
    UNION ALL SELECT 'Bon Appétit', 'bonappetit.com'
    UNION ALL SELECT 'The Boston Globe', 'bostonglobe.com'
    UNION ALL SELECT 'Maria Popova', 'brainpickings.org'
    UNION ALL SELECT 'brand eins', 'brandeins.de'
    UNION ALL SELECT 'Business Standard', 'business-standard.com'
    UNION ALL SELECT 'Business Insider', 'businessinsider.com'
    UNION ALL SELECT 'Business Insider??', 'businessinsider.in'
    UNION ALL SELECT 'Bustle', 'bustle.com'
    UNION ALL SELECT 'BuzzFeed', 'buzzfeed.com'
    UNION ALL SELECT 'BuzzFeed News', 'buzzfeednews.com'
    UNION ALL SELECT 'CBC', 'cbc.ca'
    UNION ALL SELECT 'Comic Book Resources', 'cbr.com'
    UNION ALL SELECT 'CBS News', 'cbsnews.com'
    UNION ALL SELECT 'CBS Sports', 'cbssports.com'
    UNION ALL SELECT 'Challenges', 'challenges.fr'
    UNION ALL SELECT 'Channel NewsAsia', 'channelnewsasia.com'
    UNION ALL SELECT 'Chicago Tribune', 'chicagotribune.com'
    UNION ALL SELECT 'CHIP', 'chip.de'
    UNION ALL SELECT 'Christianity Today', 'christianitytoday.com'
    UNION ALL SELECT 'The Chronicle of Higher Education', 'chronicle.com'
    UNION ALL SELECT 'Clarín', 'clarin.com'
    UNION ALL SELECT 'CNBC', 'cnbc.com'
    UNION ALL SELECT 'CNET', 'cnet.com'
    UNION ALL SELECT 'CNN', 'cnn.com'
    UNION ALL SELECT 'CNN en Español', 'cnnespanol.cnn.com'
    UNION ALL SELECT 'CoinDesk', 'coindesk.com'
    UNION ALL SELECT 'Cointelegraph', 'cointelegraph.com'
    UNION ALL SELECT 'Collaborative Fund', 'collaborativefund.com'
    UNION ALL SELECT 'Consumer Reports', 'consumerreports.org'
    UNION ALL SELECT 'The New York Times', 'cooking.nytimes.com'
    UNION ALL SELECT 'Corriere della sera', 'corriere.it'
    UNION ALL SELECT 'Cosmopolitan', 'cosmopolitan.com'
    UNION ALL SELECT 'Courrier international', 'courrierinternational.com'
    UNION ALL SELECT 'Cracked', 'cracked.com'
    UNION ALL SELECT 'Cult of Mac', 'cultofmac.com'
    UNION ALL SELECT 'Curbed', 'curbed.com'
    UNION ALL SELECT 'Daily Mail', 'dailymail.co.uk'
    UNION ALL SELECT 'Daily Record', 'dailyrecord.co.uk'
    UNION ALL SELECT 'Darius Foroux', 'dariusforoux.com'
    UNION ALL SELECT 'Dawn.com', 'dawn.com'
    UNION ALL SELECT 'Deadline Hollywood', 'deadline.com'
    UNION ALL SELECT 'Deadspin', 'deadspin.com'
    UNION ALL SELECT 'Delish', 'delish.com'
    UNION ALL SELECT 'DER STANDARD', 'derstandard.at'
    UNION ALL SELECT 'Diario de Navarra', 'diariodenavarra.es'
    UNION ALL SELECT 'Digg', 'digg.com'
    UNION ALL SELECT 'Digital Trends', 'digitaltrends.com'
    UNION ALL SELECT 'DNA India', 'dnaindia.com'
    UNION ALL SELECT 'DW', 'dw.com'
    UNION ALL SELECT 'Eater', 'eater.com'
    UNION ALL SELECT 'The Economic Times', 'economictimes.indiatimes.com'
    UNION ALL SELECT 'The Economist', 'economist.com'
    UNION ALL SELECT 'Agencia EFE', 'efe.com'
    UNION ALL SELECT 'El Comercio', 'elcomercio.es'
    UNION ALL SELECT 'El Confidencial', 'elconfidencial.com'
    UNION ALL SELECT 'elDiario.es', 'eldiario.es'
    UNION ALL SELECT 'Electrek', 'electrek.co'
    UNION ALL SELECT 'El Español', 'elespanol.com'
    UNION ALL SELECT 'Elle', 'elle.com'
    UNION ALL SELECT 'El Mundo', 'elmundo.es'
    UNION ALL SELECT 'El Universo', 'eluniverso.com'
    UNION ALL SELECT 'Engadget', 'engadget.com'
    UNION ALL SELECT 'Entrepreneur', 'entrepreneur.com'
    UNION ALL SELECT 'E! News', 'eonline.com'
    UNION ALL SELECT 'Gizmodo', 'es.gizmodo.com'
    UNION ALL SELECT 'ESPN', 'espn.com'
    UNION ALL SELECT 'Esquire', 'esquire.com'
    UNION ALL SELECT 'Eurogamer', 'eurogamer.net'
    UNION ALL SELECT 'Evernote', 'evernote.com'
    UNION ALL SELECT 'Entertainment Weekly', 'ew.com'
    UNION ALL SELECT 'Daily Express', 'express.co.uk'
    UNION ALL SELECT 'Facebook', 'facebook.com'
    UNION ALL SELECT 'Fast Company', 'fastcompany.com'
    UNION ALL SELECT 'Fatherly', 'fatherly.com'
    UNION ALL SELECT 'FAZ', 'faz.net'
    UNION ALL SELECT 'Yahoo', 'finance.yahoo.com'
    UNION ALL SELECT 'FiveThirtyEight', 'fivethirtyeight.com'
    UNION ALL SELECT 'FOCUS Online', 'focus.de'
    UNION ALL SELECT 'Food52', 'food52.com'
    UNION ALL SELECT 'The Motley Fool', 'fool.com'
    UNION ALL SELECT 'Football365', 'football365.com'
    UNION ALL SELECT 'Forbes', 'forbes.com'
    UNION ALL SELECT 'Foreign Policy', 'foreignpolicy.com'
    UNION ALL SELECT 'Fortune', 'fortune.com'
    UNION ALL SELECT 'Fox News', 'foxnews.com'
    UNION ALL SELECT 'France 24', 'france24.com'
    UNION ALL SELECT 'France Info', 'francetvinfo.fr'
    UNION ALL SELECT 'FrAndroid', 'frandroid.com'
    UNION ALL SELECT 'Shane Parrish', 'fs.blog'
    UNION ALL SELECT 'Fstoppers', 'fstoppers.com'
    UNION ALL SELECT 'Financial Times', 'ft.com'
    UNION ALL SELECT 'GameSpot', 'gamespot.com'
    UNION ALL SELECT 'Pocket', 'getpocket.com'
    UNION ALL SELECT 'Get Rich Slowly', 'getrichslowly.org'
    UNION ALL SELECT 'GIGA APPLE', 'giga.de'
    UNION ALL SELECT 'Gizmodo', 'gizmodo.com'
    UNION ALL SELECT 'Gizmodo India', 'gizmodo.com.au'
    UNION ALL SELECT 'Global News', 'globalnews.ca'
    UNION ALL SELECT 'Goal', 'goal.com'
    UNION ALL SELECT 'golem.de', 'golem.de'
    UNION ALL SELECT 'Google', 'google.co.uk'
    UNION ALL SELECT 'Google', 'google.com'
    UNION ALL SELECT 'GQ', 'gq.com'
    UNION ALL SELECT 'Grub Street', 'grubstreet.com'
    UNION ALL SELECT 'Hackaday', 'hackaday.com'
    UNION ALL SELECT 'Hacker Noon', 'hackernoon.com'
    UNION ALL SELECT 'Handelsblatt', 'handelsblatt.com'
    UNION ALL SELECT 'Harvard Business Review', 'hbr.org'
    UNION ALL SELECT 'Healthline', 'healthline.com'
    UNION ALL SELECT 'heise online', 'heise.de'
    UNION ALL SELECT 'HuffPost', 'highline.huffingtonpost.com'
    UNION ALL SELECT 'Hindustan Times', 'hindustantimes.com'
    UNION ALL SELECT 'Hipertextual', 'hipertextual.com'
    UNION ALL SELECT 'The Hollywood Reporter', 'hollywoodreporter.com'
    UNION ALL SELECT 'How-To Geek', 'howtogeek.com'
    UNION ALL SELECT 'Le HuffPost', 'huffingtonpost.fr'
    UNION ALL SELECT 'TED', 'ideas.ted.com'
    UNION ALL SELECT 'IFLScience', 'iflscience.com'
    UNION ALL SELECT 'IGN', 'ign.com'
    UNION ALL SELECT 'Il Fatto Quotidiano', 'ilfattoquotidiano.it'
    UNION ALL SELECT 'Il Post', 'ilpost.it'
    UNION ALL SELECT 'iMore', 'imore.com'
    UNION ALL SELECT 'Inc. Magazine', 'inc.com'
    UNION ALL SELECT 'The Independent', 'independent.co.uk'
    UNION ALL SELECT 'Independent.ie', 'independent.ie'
    UNION ALL SELECT 'The Indian Express', 'indianexpress.com'
    UNION ALL SELECT 'IndieWire', 'indiewire.com'
    UNION ALL SELECT 'Infobae', 'infobae.com'
    UNION ALL SELECT 'InStyle', 'instyle.com'
    UNION ALL SELECT 'Inverse', 'inverse.com'
    UNION ALL SELECT 'Investopedia', 'investopedia.com'
    UNION ALL SELECT 'iFUN', 'iphone-ticker.de'
    UNION ALL SELECT 'The Irish Times', 'irishtimes.com'
    UNION ALL SELECT 'Jacobin', 'jacobinmag.com'
    UNION ALL SELECT 'Jalopnik', 'jalopnik.com'
    UNION ALL SELECT 'James Clear', 'jamesclear.com'
    UNION ALL SELECT 'The Japan Times', 'japantimes.co.jp'
    UNION ALL SELECT 'Jeuxvideo.com', 'jeuxvideo.com'
    UNION ALL SELECT 'Jezebel', 'jezebel.com'
    UNION ALL SELECT 'Le Journal du Geek', 'journaldugeek.com'
    UNION ALL SELECT 'kicker', 'kicker.de'
    UNION ALL SELECT 'Kotaku', 'kotaku.com'
    UNION ALL SELECT 'kottke.org', 'kottke.org'
    UNION ALL SELECT 'LA NACION', 'lanacion.com.ar'
    UNION ALL SELECT 'La Presse', 'lapresse.ca'
    UNION ALL SELECT 'La Stampa', 'lastampa.it'
    UNION ALL SELECT 'Los Angeles Times', 'latimes.com'
    UNION ALL SELECT 'La Vanguardia', 'lavanguardia.com'
    UNION ALL SELECT 'Le Figaro', 'lefigaro.fr'
    UNION ALL SELECT 'Le Monde', 'lemonde.fr'
    UNION ALL SELECT 'Le Parisien', 'leparisien.fr'
    UNION ALL SELECT 'Le Point', 'lepoint.fr'
    UNION ALL SELECT 'Les Echos', 'lesechos.fr'
    UNION ALL SELECT 'Les Numériques', 'lesnumeriques.com'
    UNION ALL SELECT 'Libération', 'liberation.fr'
    UNION ALL SELECT 'Lifehacker', 'lifehacker.com'
    UNION ALL SELECT 'Lifehacker Australia', 'lifehacker.com.au'
    UNION ALL SELECT 'Listverse', 'listverse.com'
    UNION ALL SELECT 'Literary Hub', 'lithub.com'
    UNION ALL SELECT 'Mint', 'livemint.com'
    UNION ALL SELECT 'Liverpool Echo', 'liverpoolecho.co.uk'
    UNION ALL SELECT 'LIVESTRONG.COM', 'livestrong.com'
    UNION ALL SELECT 'Longreads', 'longreads.com'
    UNION ALL SELECT 'London Review of Books', 'lrb.co.uk'
    UNION ALL SELECT 'FAZ.NET - Frankfurter Allgemeine Zeitung', 'm.faz.net'
    UNION ALL SELECT 'Basecamp', 'm.signalvnoise.com'
    UNION ALL SELECT 'MacRumors', 'macrumors.com'
    UNION ALL SELECT 'MacStories', 'macstories.net'
    UNION ALL SELECT 'Macworld', 'macworld.com'
    UNION ALL SELECT 'MailChimp', 'mailchi.mp'
    UNION ALL SELECT 'MakeUseOf', 'makeuseof.com'
    UNION ALL SELECT 'MARCA', 'marca.com'
    UNION ALL SELECT 'Marginal Revolution', 'marginalrevolution.com'
    UNION ALL SELECT 'MarketWatch', 'marketwatch.com'
    UNION ALL SELECT 'Mark Manson', 'markmanson.net'
    UNION ALL SELECT 'Mashable', 'mashable.com'
    UNION ALL SELECT 'McKinsey & Company', 'mckinsey.com'
    UNION ALL SELECT 'Medical News Today', 'medicalnewstoday.com'
    UNION ALL SELECT 'Medium', 'medium.com'
    UNION ALL SELECT 'MEL Magazine', 'melmagazine.com'
    UNION ALL SELECT 'Mental Floss', 'mentalfloss.com'
    UNION ALL SELECT 'The Mercury News', 'mercurynews.com'
    UNION ALL SELECT 'Metro', 'metro.co.uk'
    UNION ALL SELECT 'Miami Herald', 'miamiherald.com'
    UNION ALL SELECT 'mindbodygreen', 'mindbodygreen.com'
    UNION ALL SELECT 'Daily Mirror', 'mirror.co.uk'
    UNION ALL SELECT 'MLB', 'mlb.com'
    UNION ALL SELECT 'CNN', 'money.cnn.com'
    UNION ALL SELECT 'moneycontrol.com', 'moneycontrol.com'
    UNION ALL SELECT 'Mother Jones', 'motherjones.com'
    UNION ALL SELECT 'Mozilla', 'mozilla.org'
    UNION ALL SELECT 'Mr. Money Mustache', 'mrmoneymustache.com'
    UNION ALL SELECT 'MSN', 'msn.com'
    UNION ALL SELECT 'MSNBC', 'msnbc.com'
    UNION ALL SELECT 'n-tv', 'n-tv.de'
    UNION ALL SELECT 'NASA - National Aeronautics and Space Administration', 'nasa.gov'
    UNION ALL SELECT 'National Geographic', 'nationalgeographic.com'
    UNION ALL SELECT 'National Post', 'nationalpost.com'
    UNION ALL SELECT 'National Review', 'nationalreview.com'
    UNION ALL SELECT 'Nature', 'nature.com'
    UNION ALL SELECT 'Nautilus', 'nautil.us'
    UNION ALL SELECT 'NBC News', 'nbcnews.com'
    UNION ALL SELECT 'New Atlas', 'newatlas.com'
    UNION ALL SELECT 'The New Republic', 'newrepublic.com'
    UNION ALL SELECT 'Sky', 'news.sky.com'
    UNION ALL SELECT 'New Scientist', 'newscientist.com'
    UNION ALL SELECT 'New Statesman', 'newstatesman.com'
    UNION ALL SELECT 'Newsweek', 'newsweek.com'
    UNION ALL SELECT 'The New Yorker', 'newyorker.com'
    UNION ALL SELECT 'NPR', 'npr.org'
    UNION ALL SELECT 'Numerama', 'numerama.com'
    UNION ALL SELECT 'The New York Review of Books', 'nybooks.com'
    UNION ALL SELECT 'New York Magazine', 'nymag.com'
    UNION ALL SELECT 'New York Post', 'nypost.com'
    UNION ALL SELECT 'The New York Times', 'nytimes.com'
    UNION ALL SELECT 'The New Zealand Herald', 'nzherald.co.nz'
    UNION ALL SELECT 'NZZ', 'nzz.ch'
    UNION ALL SELECT 'Observer Media', 'observer.com'
    UNION ALL SELECT 'Lifehacker', 'offspring.lifehacker.com'
    UNION ALL SELECT 'OKDIARIO', 'okdiario.com'
    UNION ALL SELECT 'Spotify', 'open.spotify.com'
    UNION ALL SELECT 'Open Culture', 'openculture.com'
    UNION ALL SELECT 'Ouest-France', 'ouest-france.fr'
    UNION ALL SELECT 'Outside', 'outsideonline.com'
    UNION ALL SELECT 'Page Six', 'pagesix.com'
    UNION ALL SELECT 'Paste Magazine', 'pastemagazine.com'
    UNION ALL SELECT 'PBS', 'pbs.org'
    UNION ALL SELECT 'PC Gamer', 'pcgamer.com'
    UNION ALL SELECT 'PCM', 'pcmag.com'
    UNION ALL SELECT 'PCWorld', 'pcworld.com'
    UNION ALL SELECT 'People', 'people.com'
    UNION ALL SELECT 'PetaPixel', 'petapixel.com'
    UNION ALL SELECT 'Phys.org', 'phys.org'
    UNION ALL SELECT 'Pitchfork', 'pitchfork.com'
    UNION ALL SELECT 'POLITICO', 'politico.com'
    UNION ALL SELECT 'POLITICO Europe', 'politico.eu'
    UNION ALL SELECT 'Polygon', 'polygon.com'
    UNION ALL SELECT 'Popular Science', 'popsci.com'
    UNION ALL SELECT 'PS', 'popsugar.com'
    UNION ALL SELECT 'Popular Mechanics', 'popularmechanics.com'
    UNION ALL SELECT 'Presse-citron', 'presse-citron.net'
    UNION ALL SELECT 'NBC Sports', 'profootballtalk.nbcsports.com'
    UNION ALL SELECT 'Project Syndicate', 'project-syndicate.org'
    UNION ALL SELECT 'ProPublica', 'propublica.org'
    UNION ALL SELECT 'Psychology Today', 'psychologytoday.com'
    UNION ALL SELECT 'Quanta Magazine', 'quantamagazine.org'
    UNION ALL SELECT 'Quillette', 'quillette.com'
    UNION ALL SELECT 'Quartz', 'qz.com'
    UNION ALL SELECT 'Racked', 'racked.com'
    UNION ALL SELECT 'Reason', 'reason.com'
    UNION ALL SELECT 'Reddit', 'reddit.com'
    UNION ALL SELECT 'Refinery29', 'refinery29.com'
    UNION ALL SELECT 'la Repubblica', 'repubblica.it'
    UNION ALL SELECT 'Reuters', 'reuters.com'
    UNION ALL SELECT 'Rock, Paper, Shotgun', 'rockpapershotgun.com'
    UNION ALL SELECT 'Rolling Stone', 'rollingstone.com'
    UNION ALL SELECT 'Salon', 'salon.com'
    UNION ALL SELECT 'SB Nation', 'sbnation.com'
    UNION ALL SELECT 'ScienceAlert', 'sciencealert.com'
    UNION ALL SELECT 'Scientific American', 'scientificamerican.com'
    UNION ALL SELECT 'South China Morning Post', 'scmp.com'
    UNION ALL SELECT 'Screen Rant', 'screenrant.com'
    UNION ALL SELECT 'The Seattle Times', 'seattletimes.com'
    UNION ALL SELECT 'Serious Eats', 'seriouseats.com'
    UNION ALL SELECT 'SFGate', 'sfgate.com'
    UNION ALL SELECT 'Shape', 'shape.com'
    UNION ALL SELECT 'Sports Illustrated', 'si.com'
    UNION ALL SELECT 'Skift', 'skift.com'
    UNION ALL SELECT '/Film', 'slashfilm.com'
    UNION ALL SELECT 'Slate', 'slate.com'
    UNION ALL SELECT 'Slate France', 'slate.fr'
    UNION ALL SELECT 'The Sydney Morning Herald', 'smh.com.au'
    UNION ALL SELECT 'Smithsonian Magazine', 'smithsonianmag.com'
    UNION ALL SELECT 'So Foot', 'sofoot.com'
    UNION ALL SELECT 'Southern Living', 'southernliving.com'
    UNION ALL SELECT 'Spektrum', 'spektrum.de'
    UNION ALL SELECT 'DER SPIEGEL', 'spiegel.de'
    UNION ALL SELECT 'Splinter', 'splinternews.com'
    UNION ALL SELECT 'Yahoo', 'sports.yahoo.com'
    UNION ALL SELECT 'CaschysBlog', 'stadt-bremerhaven.de'
    UNION ALL SELECT 'Evening Standard', 'standard.co.uk'
    UNION ALL SELECT 'Star Tribune', 'startribune.com'
    UNION ALL SELECT 'Stereogum', 'stereogum.com'
    UNION ALL SELECT 'Buffer', 'stories.buffer.com'
    UNION ALL SELECT 'Stratechery', 'stratechery.com'
    UNION ALL SELECT 'Süddeutsche Zeitung', 'sueddeutsche.de'
    UNION ALL SELECT 't3n Magazin', 't3n.de'
    UNION ALL SELECT 'tagesschau', 'tagesschau.de'
    UNION ALL SELECT 'Tagesspiegel', 'tagesspiegel.de'
    UNION ALL SELECT 'taz', 'taz.de'
    UNION ALL SELECT 'TechCrunch', 'techcrunch.com'
    UNION ALL SELECT 'MIT Technology Review', 'technologyreview.com'
    UNION ALL SELECT 'TechRadar', 'techradar.com'
    UNION ALL SELECT 'The Telegraph', 'telegraph.co.uk'
    UNION ALL SELECT 'Texas Monthly', 'texasmonthly.com'
    UNION ALL SELECT 'The Age', 'theage.com.au'
    UNION ALL SELECT 'The American Conservative', 'theamericanconservative.com'
    UNION ALL SELECT 'The Athletic', 'theathletic.com'
    UNION ALL SELECT 'The Atlantic', 'theatlantic.com'
    UNION ALL SELECT 'The Baffler', 'thebaffler.com'
    UNION ALL SELECT 'The Conversation', 'theconversation.com'
    UNION ALL SELECT 'The Cut', 'thecut.com'
    UNION ALL SELECT 'The Daily Beast', 'thedailybeast.com'
    UNION ALL SELECT 'The Globe and Mail', 'theglobeandmail.com'
    UNION ALL SELECT 'The Guardian', 'theguardian.com'
    UNION ALL SELECT 'The Hill', 'thehill.com'
    UNION ALL SELECT 'The Hindu', 'thehindu.com'
    UNION ALL SELECT 'Business Line', 'thehindubusinessline.com'
    UNION ALL SELECT 'The Intercept', 'theintercept.com'
    UNION ALL SELECT 'The Kitchn', 'thekitchn.com'
    UNION ALL SELECT 'Ladders', 'theladders.com'
    UNION ALL SELECT 'The Nation', 'thenation.com'
    UNION ALL SELECT 'The Next Web', 'thenextweb.com'
    UNION ALL SELECT 'The Outline', 'theoutline.com'
    UNION ALL SELECT 'The Paris Review', 'theparisreview.org'
    UNION ALL SELECT 'The Ringer', 'theringer.com'
    UNION ALL SELECT 'The Root', 'theroot.com'
    UNION ALL SELECT 'Toronto Star', 'thestar.com'
    UNION ALL SELECT 'The Sun', 'thesun.co.uk'
    UNION ALL SELECT 'The Takeout', 'thetakeout.com'
    UNION ALL SELECT 'The Times', 'thetimes.co.uk'
    UNION ALL SELECT 'The Verge', 'theverge.com'
    UNION ALL SELECT 'The Walrus', 'thewalrus.ca'
    UNION ALL SELECT 'The Week', 'theweek.com'
    UNION ALL SELECT 'TheWire.in', 'thewire.in'
    UNION ALL SELECT 'Thrillist', 'thrillist.com'
    UNION ALL SELECT 'Thrive Global', 'thriveglobal.com'
    UNION ALL SELECT 'Time', 'time.com'
    UNION ALL SELECT 'The Times of India', 'timesofindia.indiatimes.com'
    UNION ALL SELECT 'Tiny Buddha', 'tinybuddha.com'
    UNION ALL SELECT 'Towards Data Science', 'towardsdatascience.com'
    UNION ALL SELECT 'Travel + Leisure', 'travelandleisure.com'
    UNION ALL SELECT 'Lifehacker', 'twocents.lifehacker.com'
    UNION ALL SELECT 'UPROXX', 'uproxx.com'
    UNION ALL SELECT 'USA TODAY', 'usatoday.com'
    UNION ALL SELECT 'UX Collective', 'uxdesign.cc'
    UNION ALL SELECT 'Vanity Fair', 'vanityfair.com'
    UNION ALL SELECT 'Variety', 'variety.com'
    UNION ALL SELECT 'VentureBeat', 'venturebeat.com'
    UNION ALL SELECT 'VICE', 'vice.com'
    UNION ALL SELECT 'Lifehacker', 'vitals.lifehacker.com'
    UNION ALL SELECT 'Vogue', 'vogue.com'
    UNION ALL SELECT 'Vox', 'vox.com'
    UNION ALL SELECT 'Vulture', 'vulture.com'
    UNION ALL SELECT 'Wait But Why', 'waitbutwhy.com'
    UNION ALL SELECT 'The Washington Post', 'washingtonpost.com'
    UNION ALL SELECT 'WBUR', 'wbur.org'
    UNION ALL SELECT 'World Economic Forum', 'weforum.org'
    UNION ALL SELECT 'WELT', 'welt.de'
    UNION ALL SELECT 'WIRED UK', 'wired.co.uk'
    UNION ALL SELECT 'WIRED', 'wired.com'
    UNION ALL SELECT 'The Wall Street Journal', 'wsj.com'
    UNION ALL SELECT 'Xataka', 'xataka.com'
    UNION ALL SELECT 'XDA Developers', 'xda-developers.com'
    UNION ALL SELECT 'Yahoo', 'yahoo.com'
    UNION ALL SELECT 'YouTube', 'youtube.com'
    UNION ALL SELECT 'ZDNet', 'zdnet.com'
    UNION ALL SELECT 'DIE ZEIT', 'zeit.de'
    UNION ALL SELECT 'Zen Habits', 'zenhabits.net'
    UNION ALL SELECT '01net', '01net.com'
    UNION ALL SELECT '11FREUNDE', '11freunde.de'
    UNION ALL SELECT 'The 19th', '19thnews.org'
    UNION ALL SELECT '1E9', '1e9.community'
    UNION ALL SELECT '20minutos', '20minutos.es'
    UNION ALL SELECT '3sat', '3sat.de'
    UNION ALL SELECT '404 Media', '404media.co'
    UNION ALL SELECT '5280 Magazine', '5280.com'
    UNION ALL SELECT '54books', '54books.de'
    UNION ALL SELECT '90min', '90min.com'
    UNION ALL SELECT 'Andreessen Horowitz', 'a16z.com'
    UNION ALL SELECT 'AARP', 'aarp.org'
    UNION ALL SELECT 'Hamburger Abendblatt', 'abendblatt.de'
    UNION ALL SELECT 'AD', 'ad-italia.it'
    UNION ALL SELECT 'AD Magazin', 'ad-magazin.de'
    UNION ALL SELECT 'AD France', 'admagazine.fr'
    UNION ALL SELECT 'Adnkronos', 'adnkronos.com'
    UNION ALL SELECT 'AFAR', 'afar.com'
    UNION ALL SELECT 'Africa Is a Country', 'africasacountry.com'
    UNION ALL SELECT 'AFRO', 'afro.com'
    UNION ALL SELECT 'Agi - Agenzia Italia', 'agi.it'
    UNION ALL SELECT 'Agrodolce', 'agrodolce.it'
    UNION ALL SELECT 'Alley Oop', 'alleyoop.ilsole24ore.com'
    UNION ALL SELECT 'Tufan.co', 'allgemeine-zeitung.de'
    UNION ALL SELECT 'Allrecipes', 'allrecipes.com'
    UNION ALL SELECT 'Andscape', 'andscape.com'
    UNION ALL SELECT 'annabelle', 'annabelle.ch'
    UNION ALL SELECT 'Apotheken Umschau', 'apotheken-umschau.de'
    UNION ALL SELECT 'Arbeits-ABC', 'arbeits-abc.de'
    UNION ALL SELECT 'Architectural Digest', 'architecturaldigest.com'
    UNION ALL SELECT 'AD India', 'architecturaldigest.in'
    UNION ALL SELECT 'ARD alpha', 'ardalpha.de'
    UNION ALL SELECT 'arte Magazin', 'arte-magazin.de'
    UNION ALL SELECT 'arte', 'arte.tv'
    UNION ALL SELECT 'Artribune', 'artribune.com'
    UNION ALL SELECT 'The Nikkei', 'asia.nikkei.com'
    UNION ALL SELECT 'Audubon Magazine', 'audubon.org'
    UNION ALL SELECT 'Augsburger Allgemeine', 'augsburger-allgemeine.de'
    UNION ALL SELECT 'Autobild', 'autobild.es'
    UNION ALL SELECT 'Autopista', 'autopista.es'
    UNION ALL SELECT 'Autosport', 'autosport.com'
    UNION ALL SELECT 'Avvenire', 'avvenire.it'
    UNION ALL SELECT 'The Arizona Republic', 'azcentral.com'
    UNION ALL SELECT 'Backpacker', 'backpacker.com'
    UNION ALL SELECT 'Barcelona Secreta', 'barcelonasecreta.com'
    UNION ALL SELECT 'Baseball America', 'baseballamerica.com'
    UNION ALL SELECT 'RealGM', 'basketball.realgm.com'
    UNION ALL SELECT 'BBC Good Food', 'bbcgoodfood.com'
    UNION ALL SELECT 'Beaux Arts Magazine', 'beauxarts.com'
    UNION ALL SELECT 'Bebés y Más', 'bebesymas.com'
    UNION ALL SELECT 'Joshua Becker', 'becomingminimalist.com'
    UNION ALL SELECT 'Behavioral Scientist', 'behavioralscientist.org'
    UNION ALL SELECT 'NZZ Bellevue', 'bellevue.nzz.ch'
    UNION ALL SELECT 'BFMTV', 'bfmtv.com'
    UNION ALL SELECT 'Better Homes & Gardens', 'bhg.com'
    UNION ALL SELECT 'BioGraphic', 'biographic.com'
    UNION ALL SELECT 'Mozilla', 'blog.mozilla.org'
    UNION ALL SELECT 'RescueTime', 'blog.rescuetime.com'
    UNION ALL SELECT 'El Confidencial', 'blogs.elconfidencial.com'
    UNION ALL SELECT 'BookPage', 'bookpage.com'
    UNION ALL SELECT 'Book Riot', 'bookriot.com'
    UNION ALL SELECT 'Boston.com', 'boston.com'
    UNION ALL SELECT 'Boston', 'bostonmagazine.com'
    UNION ALL SELECT 'Boston Review', 'bostonreview.net'
    UNION ALL SELECT 'BR', 'br.de'
    UNION ALL SELECT 'Brigitte', 'brigitte.de'
    UNION ALL SELECT 'Business Punk', 'business-punk.com'
    UNION ALL SELECT 'Business Insider', 'businessinsider.de'
    UNION ALL SELECT 'Business Insider', 'businessinsider.es'
    UNION ALL SELECT 'The Business of Fashion', 'businessoffashion.com'
    UNION ALL SELECT 'BuzzFeed', 'buzzfeed.de'
    UNION ALL SELECT 'Canary Media', 'canarymedia.com'
    UNION ALL SELECT 'Capital', 'capital.de'
    UNION ALL SELECT 'Capital B', 'capitalbnews.org'
    UNION ALL SELECT 'Car and Driver', 'caranddriver.com'
    UNION ALL SELECT 'Caught Offside', 'caughtoffside.com'
    UNION ALL SELECT 'Chicago Sun-Times', 'chicago.suntimes.com'
    UNION ALL SELECT 'Chicago Reader', 'chicagoreader.com'
    UNION ALL SELECT 'Chicago Review of Books', 'chireviewofbooks.com'
    UNION ALL SELECT 'CiboToday', 'cibotoday.it'
    UNION ALL SELECT 'Civil Eats', 'civileats.com'
    UNION ALL SELECT 'Columbia Journalism Review', 'cjr.org'
    UNION ALL SELECT 'Clubic', 'clubic.com'
    UNION ALL SELECT 'Condé Nast Traveler', 'cntraveler.com'
    UNION ALL SELECT 'Condé Nast Traveller', 'cntraveller.com'
    UNION ALL SELECT 'Condé Nast Traveller', 'cntraveller.de'
    UNION ALL SELECT 'Condé Nast Traveller India', 'cntraveller.in'
    UNION ALL SELECT 'Collider', 'collider.com'
    UNION ALL SELECT 'Complex', 'complex.com'
    UNION ALL SELECT 'ComputerBase', 'computerbase.de'
    UNION ALL SELECT 'Computer Hoy', 'computerhoy.20minutos.es'
    UNION ALL SELECT 'Computer Hoy', 'computerhoy.com'
    UNION ALL SELECT 'Computer Weekly', 'computerweekly.com'
    UNION ALL SELECT 'Computerworld', 'computerworld.com'
    UNION ALL SELECT 'Con Mucha Gula', 'conmuchagula.com'
    UNION ALL SELECT 'Consequence', 'consequence.net'
    UNION ALL SELECT 'Context', 'context.news'
    UNION ALL SELECT 'CORRECTIV', 'correctiv.org'
    UNION ALL SELECT 'Corriere dello sport', 'corrieredellosport.it'
    UNION ALL SELECT 'COSMOS', 'cosmosmagazine.com'
    UNION ALL SELECT 'Country Living', 'countryliving.com'
    UNION ALL SELECT 'CrimeReads', 'crimereads.com'
    UNION ALL SELECT 'El Español', 'cronicaglobal.elespanol.com'
    UNION ALL SELECT 'The Christian Science Monitor', 'csmonitor.com'
    UNION ALL SELECT 'CTV News', 'ctvnews.ca'
    UNION ALL SELECT 'Culture.org', 'culture.org'
    UNION ALL SELECT 'Current Affairs', 'currentaffairs.org'
    UNION ALL SELECT 'JSTOR Daily', 'daily.jstor.org'
    UNION ALL SELECT 'Das Erste', 'daserste.de'
    UNION ALL SELECT 'Dazed', 'dazeddigital.com'
    UNION ALL SELECT 'DDay', 'dday.it'
    UNION ALL SELECT 'Euronews Deutsch', 'de.euronews.com'
    UNION ALL SELECT 'Decider', 'decider.com'
    UNION ALL SELECT 'dekoder', 'dekoder.org'
    UNION ALL SELECT 'Den Of Geek', 'denofgeek.com'
    UNION ALL SELECT 'DER STANDARD', 'derstandard.de'
    UNION ALL SELECT 'designboom', 'designboom.com'
    UNION ALL SELECT 'Deutschlandfunk', 'deutschlandfunk.de'
    UNION ALL SELECT 'Deutschlandfunk Kultur', 'deutschlandfunkkultur.de'
    UNION ALL SELECT 'Deutschlandfunk Nova', 'deutschlandfunknova.de'
    UNION ALL SELECT 'Dezeen', 'dezeen.com'
    UNION ALL SELECT 'Die Presse', 'diepresse.com'
    UNION ALL SELECT 'DIFFUS', 'diffus.de'
    UNION ALL SELECT 'DIFFUS', 'diffusmag.de'
    UNION ALL SELECT 'Dire', 'dire.it'
    UNION ALL SELECT 'Directo al Paladar', 'directoalpaladar.com'
    UNION ALL SELECT 'Discover', 'discovermagazine.com'
    UNION ALL SELECT 'BBC Wildlife', 'discoverwildlife.com'
    UNION ALL SELECT 'Dissapore', 'dissapore.com'
    UNION ALL SELECT 'DIYPhotography', 'diyphotography.net'
    UNION ALL SELECT 'Domino', 'domino.com'
    UNION ALL SELECT 'DUMMY', 'dummy-magazin.de'
    UNION ALL SELECT 'Dwell', 'dwell.com'
    UNION ALL SELECT 'Eat this', 'eat-this.org'
    UNION ALL SELECT 'Eating Well', 'eatingwell.com'
    UNION ALL SELECT 'EBONY', 'ebony.com'
    UNION ALL SELECT 'CNN', 'edition.cnn.com'
    UNION ALL SELECT 'EDITION F', 'editionf.com'
    UNION ALL SELECT 'Editoriale Domani', 'editorialedomani.it'
    UNION ALL SELECT 'Education Week', 'edweek.org'
    UNION ALL SELECT 'Effilee', 'effilee.de'
    UNION ALL SELECT 'einfach tasty', 'einfach-tasty.de'
    UNION ALL SELECT 'El Blog Salmón', 'elblogsalmon.com'
    UNION ALL SELECT 'El Correo', 'elcorreo.com'
    UNION ALL SELECT 'elEconomista.es', 'eleconomista.es'
    UNION ALL SELECT 'Electric Literature', 'electricliterature.com'
    UNION ALL SELECT 'El Independiente', 'elindependiente.com'
    UNION ALL SELECT 'ELLE', 'elle.de'
    UNION ALL SELECT 'Elle', 'elle.fr'
    UNION ALL SELECT 'ELLE Decor', 'elledecor.com'
    UNION ALL SELECT 'El Periódico', 'elperiodico.com'
    UNION ALL SELECT 'Eltern', 'eltern.de'
    UNION ALL SELECT 'emotion', 'emotion.de'
    UNION ALL SELECT 'Empire', 'empireonline.com'
    UNION ALL SELECT 'Le Figaro Emploi', 'emploi.lefigaro.fr'
    UNION ALL SELECT 'Epicurious', 'epicurious.com'
    UNION ALL SELECT 'The Equalizer', 'equalizersoccer.com'
    UNION ALL SELECT 'Yahoo! Finanzas', 'es-us.finanzas.yahoo.com'
    UNION ALL SELECT 'Euronews Español', 'es.euronews.com'
    UNION ALL SELECT 'IGN España', 'es.ign.com'
    UNION ALL SELECT 'Knowable en Español', 'es.knowablemagazine.org'
    UNION ALL SELECT 'WIRED', 'es.wired.com'
    UNION ALL SELECT 'The Escapist', 'escapistmagazine.com'
    UNION ALL SELECT 'Espinof', 'espinof.com'
    UNION ALL SELECT 'ESPN UK', 'espn.co.uk'
    UNION ALL SELECT 'Esquire', 'esquire.de'
    UNION ALL SELECT 'Essence', 'essence.com'
    UNION ALL SELECT 'Ethic', 'ethic.es'
    UNION ALL SELECT 'Le Figaro Etudiant', 'etudiant.lefigaro.fr'
    UNION ALL SELECT 'Eurohoops.net', 'eurohoops.net'
    UNION ALL SELECT 'Euronews', 'euronews.com'
    UNION ALL SELECT 'Europa Press', 'europapress.es'
    UNION ALL SELECT 'Eurozine', 'eurozine.com'
    UNION ALL SELECT 'Everyeye', 'everyeye.it'
    UNION ALL SELECT 'Expansión', 'expansion.com'
    UNION ALL SELECT 'Extra', 'extratv.com'
    UNION ALL SELECT 'falstaff', 'falstaff.com'
    UNION ALL SELECT 'Far Out Magazine', 'faroutmagazine.co.uk'
    UNION ALL SELECT 'ProPublica', 'features.propublica.org'
    UNION ALL SELECT 'Der Feinschmecker', 'feinschmecker.de'
    UNION ALL SELECT 'Version Femina', 'femina.fr'
    UNION ALL SELECT 'Femme Actuelle', 'femmeactuelle.fr'
    UNION ALL SELECT 'The Financial Express', 'financialexpress.com'
    UNION ALL SELECT 'Financial Samurai', 'financialsamurai.com'
    UNION ALL SELECT 'Firstpost', 'firstpost.com'
    UNION ALL SELECT 'First Things', 'firstthings.com'
    UNION ALL SELECT 'FIT FOR FUN', 'fitforfun.de'
    UNION ALL SELECT 'Five Books', 'fivebooks.com'
    UNION ALL SELECT 'FlowingData', 'flowingdata.com'
    UNION ALL SELECT 'fluter', 'fluter.de'
    UNION ALL SELECT 'Focus', 'focus.it'
    UNION ALL SELECT 'Food & Wine', 'foodandwine.com'
    UNION ALL SELECT 'Forbes India', 'forbesindia.com'
    UNION ALL SELECT 'Foreign Affairs', 'foreignaffairs.com'
    UNION ALL SELECT 'Fortune India', 'fortuneindia.com'
    UNION ALL SELECT 'Fotogramas', 'fotogramas.es'
    UNION ALL SELECT 'FourFourTwo', 'fourfourtwo.com'
    UNION ALL SELECT 'FOX SPORTS', 'foxsports.com'
    UNION ALL SELECT 'Frankfurter Rundschau', 'fr.de'
    UNION ALL SELECT 'Euronews Français', 'fr.euronews.com'
    UNION ALL SELECT 'Detroit Free Press', 'freep.com'
    UNION ALL SELECT 'der Freitag', 'freitag.de'
    UNION ALL SELECT 'freundin', 'freundin.de'
    UNION ALL SELECT 'Futura-Sciences', 'futura-sciences.com'
    UNION ALL SELECT 'futurezone', 'futurezone.at'
    UNION ALL SELECT 'Futurism', 'futurism.com'
    UNION ALL SELECT 'Gambero Rosso', 'gamberorosso.it'
    UNION ALL SELECT 'Game Informer', 'gameinformer.com'
    UNION ALL SELECT 'Gamekult', 'gamekult.com'
    UNION ALL SELECT 'GameStar', 'gamestar.de'
    UNION ALL SELECT 'Gastrolab', 'gastrolabweb.es'
    UNION ALL SELECT 'Bill Gates', 'gatesnotes.com'
    UNION ALL SELECT 'Gazzetta', 'gazzetta.it'
    UNION ALL SELECT 'GeekyGadgets', 'geeky-gadgets.com'
    UNION ALL SELECT 'Gematsu', 'gematsu.com'
    UNION ALL SELECT 'Genbeta', 'genbeta.com'
    UNION ALL SELECT 'GEO', 'geo.de'
    UNION ALL SELECT 'Géo', 'geo.fr'
    UNION ALL SELECT 'Geopop', 'geopop.it'
    UNION ALL SELECT 'Geschichte der Gegenwart', 'geschichtedergegenwart.ch'
    UNION ALL SELECT 'Get Surrey', 'getsurrey.co.uk'
    UNION ALL SELECT 'Glamour', 'glamour.com'
    UNION ALL SELECT 'Glamour', 'glamour.de'
    UNION ALL SELECT 'Glamour', 'glamour.es'
    UNION ALL SELECT 'GoogleWatchBlog', 'googlewatchblog.de'
    UNION ALL SELECT 'GQ', 'gq-magazin.de'
    UNION ALL SELECT 'British GQ', 'gq-magazine.co.uk'
    UNION ALL SELECT 'GQ Italia', 'gqitalia.it'
    UNION ALL SELECT 'GQ France', 'gqmagazine.fr'
    UNION ALL SELECT 'Granta', 'granta.com'
    UNION ALL SELECT 'Greater Good Magazine', 'greatergood.berkeley.edu'
    UNION ALL SELECT 'Grist', 'grist.org'
    UNION ALL SELECT 'Haaretz', 'haaretz.com'
    UNION ALL SELECT 'Health', 'health.com'
    UNION ALL SELECT 'Highsnobiety', 'highsnobiety.com'
    UNION ALL SELECT 'Historia National Geographic', 'historia.nationalgeographic.com.es'
    UNION ALL SELECT 'Sky History', 'history.co.uk'
    UNION ALL SELECT 'HISTORY', 'history.com'
    UNION ALL SELECT 'History Extra', 'historyextra.com'
    UNION ALL SELECT 'History Today', 'historytoday.com'
    UNION ALL SELECT 'HODINKEE', 'hodinkee.com'
    UNION ALL SELECT 'Hörspiel und Feature', 'hoerspielundfeature.de'
    UNION ALL SELECT 'Hollywood Life', 'hollywoodlife.com'
    UNION ALL SELECT 'Homes & Gardens', 'homesandgardens.com'
    UNION ALL SELECT 'Hoops Rumors', 'hoopsrumors.com'
    UNION ALL SELECT 'Hoops Wire', 'hoopswire.com'
    UNION ALL SELECT 'House & Garden', 'houseandgarden.co.uk'
    UNION ALL SELECT 'House Beautiful', 'housebeautiful.com'
    UNION ALL SELECT 'HuffPost UK', 'huffingtonpost.co.uk'
    UNION ALL SELECT 'HuffPost Italia', 'huffingtonpost.it'
    UNION ALL SELECT 'HuffPost', 'huffpost.com'
    UNION ALL SELECT 'VICE', 'i-d.vice.com'
    UNION ALL SELECT 'iFUN', 'ifun.de'
    UNION ALL SELECT 'Il Libraio', 'illibraio.it'
    UNION ALL SELECT 'Il Messagero', 'ilmessaggero.it'
    UNION ALL SELECT 'Il Sole 24 ORE', 'ilsole24ore.com'
    UNION ALL SELECT 'Il Tascabile', 'iltascabile.com'
    UNION ALL SELECT 'Le Figaro Immobilier', 'immobilier.lefigaro.fr'
    UNION ALL SELECT 'India.com', 'india.com'
    UNION ALL SELECT 'India Today', 'indiatoday.in'
    UNION ALL SELECT 'Info Data', 'infodata.ilsole24ore.com'
    UNION ALL SELECT 'Inhabitat', 'inhabitat.com'
    UNION ALL SELECT 'Inside Higher Ed', 'insidehighered.com'
    UNION ALL SELECT 'InStyle', 'instyle.de'
    UNION ALL SELECT 'Internazionale', 'internazionale.it'
    UNION ALL SELECT 'iO Donna', 'iodonna.it'
    UNION ALL SELECT 'Euronews Italiano', 'it.euronews.com'
    UNION ALL SELECT 'It’s Nice That', 'itsnicethat.com'
    UNION ALL SELECT 'SZ JETZT', 'jetzt.de'
    UNION ALL SELECT 'JoBlo', 'joblo.com'
    UNION ALL SELECT 'Jot Down', 'jotdown.es'
    UNION ALL SELECT 'Jüdische Allgemeine', 'juedische-allgemeine.de'
    UNION ALL SELECT 'KFF Health News', 'kffhealthnews.org'
    UNION ALL SELECT 'Kiplinger', 'kiplinger.com'
    UNION ALL SELECT 'Knowable Magazine', 'knowablemagazine.org'
    UNION ALL SELECT 'Konbini', 'konbini.com'
    UNION ALL SELECT 'Korii', 'korii.slate.fr'
    UNION ALL SELECT 'Krautreporter', 'krautreporter.de'
    UNION ALL SELECT 'briankrebs', 'krebsonsecurity.com'
    UNION ALL SELECT 'La Croix', 'la-croix.com'
    UNION ALL SELECT 'La Cucina Italiana', 'lacucinaitaliana.it'
    UNION ALL SELECT 'L’ADN', 'ladn.eu'
    UNION ALL SELECT 'La mente es maravillosa', 'lamenteesmaravillosa.com'
    UNION ALL SELECT 'La Razón', 'larazon.es'
    UNION ALL SELECT 'Los Angeles Review of Books', 'lareviewofbooks.org'
    UNION ALL SELECT 'Larry Brown Sports', 'larrybrownsports.com'
    UNION ALL SELECT 'La Svolta', 'lasvolta.it'
    UNION ALL SELECT 'La Voix du Nord', 'lavoixdunord.fr'
    UNION ALL SELECT 'Lega Nerd', 'leganerd.com'
    UNION ALL SELECT 'Le JDD', 'lejdd.fr'
    UNION ALL SELECT 'Le Progrès', 'leprogres.fr'
    UNION ALL SELECT 'Le Scienze', 'lescienze.it'
    UNION ALL SELECT 'LessWrong', 'lesswrong.com'
    UNION ALL SELECT 'Le Temps', 'letemps.ch'
    UNION ALL SELECT 'Linkiesta', 'linkiesta.it'
    UNION ALL SELECT 'Live Science', 'livescience.com'
    UNION ALL SELECT 'Living', 'living.corriere.it'
    UNION ALL SELECT 'Livingetc', 'livingetc.com'
    UNION ALL SELECT 'Lonely Planet', 'lonelyplanet.com'
    UNION ALL SELECT 'Loudwire', 'loudwire.com'
    UNION ALL SELECT 'LTO', 'lto.de'
    UNION ALL SELECT 'Little White Lies', 'lwlies.com'
    UNION ALL SELECT 'Mac4Ever /Apple&Tech', 'mac4ever.com'
    UNION ALL SELECT 'Maclean’s', 'macleans.ca'
    UNION ALL SELECT 'Madame Figaro', 'madame.lefigaro.fr'
    UNION ALL SELECT 'Madrid Secreto', 'madridsecreto.co'
    UNION ALL SELECT 'zenith', 'magazin.zenith.me'
    UNION ALL SELECT 'Atavist', 'magazine.atavist.com'
    UNION ALL SELECT 'manager magazin', 'manager-magazin.de'
    UNION ALL SELECT 'Marie Claire UK', 'marieclaire.co.uk'
    UNION ALL SELECT 'Marie Claire', 'marieclaire.com'
    UNION ALL SELECT 'Marie Claire', 'marieclaire.fr'
    UNION ALL SELECT 'Marie Claire', 'marieclaire.it'
    UNION ALL SELECT 'Martha Stewart', 'marthastewart.com'
    UNION ALL SELECT 'Mashed', 'mashed.com'
    UNION ALL SELECT 'mdr', 'mdr.de'
    UNION ALL SELECT 'Mediapart', 'mediapart.fr'
    UNION ALL SELECT 'MERIAN', 'merian.de'
    UNION ALL SELECT 'Merkur', 'merkur.de'
    UNION ALL SELECT 'Mía', 'miarevista.es'
    UNION ALL SELECT 'The Missouri Review', 'missourireview.com'
    UNION ALL SELECT 'MLB Trade Rumors', 'mlbtraderumors.com'
    UNION ALL SELECT 'moment.at', 'moment.at'
    UNION ALL SELECT 'Money', 'money.com'
    UNION ALL SELECT 'monopol', 'monopol-magazin.de'
    UNION ALL SELECT 'Monsters and Critics', 'monstersandcritics.com'
    UNION ALL SELECT 'Berliner Morgenpost', 'morgenpost.de'
    UNION ALL SELECT 'Morningstar', 'morningstar.com'
    UNION ALL SELECT 'Motherly', 'mother.ly'
    UNION ALL SELECT 'Moviepilot', 'moviepilot.de'
    UNION ALL SELECT 'Mundo Deportivo', 'mundodeportivo.com'
    UNION ALL SELECT 'musikexpress', 'musikexpress.de'
    UNION ALL SELECT 'Muy Interesante', 'muyinteresante.com'
    UNION ALL SELECT 'Muy Interesante', 'muyinteresante.es'
    UNION ALL SELECT 'MYP Magazine', 'myp-magazine.com'
    UNION ALL SELECT 'MyRecipes', 'myrecipes.com'
    UNION ALL SELECT 'NachDenkSeiten', 'nachdenkseiten.de'
    UNION ALL SELECT 'National Geographic España', 'nationalgeographic.com.es'
    UNION ALL SELECT 'NATIONAL GEOGRAPHIC', 'nationalgeographic.de'
    UNION ALL SELECT 'National Geographic France', 'nationalgeographic.fr'
    UNION ALL SELECT 'National Geographic', 'nationalgeographic.it'
    UNION ALL SELECT 'The National Interest', 'nationalinterest.org'
    UNION ALL SELECT 'National Basketball Association', 'nba.com'
    UNION ALL SELECT 'NBC Sports', 'nbcsports.com'
    UNION ALL SELECT 'NDR', 'ndr.de'
    UNION ALL SELECT 'NDTV', 'ndtv.com'
    UNION ALL SELECT 'Neon Mag', 'neonmag.fr'
    UNION ALL SELECT 'Netflix', 'netflix.com'
    UNION ALL SELECT 'netzpolitik.org', 'netzpolitik.org'
    UNION ALL SELECT 'netzwelt', 'netzwelt.de'
    UNION ALL SELECT 'News18', 'news18.com'
    UNION ALL SELECT 'NewsLab', 'newslab.org'
    UNION ALL SELECT 'Newtral', 'newtral.es'
    UNION ALL SELECT 'Next Avenue', 'nextavenue.org'
    UNION ALL SELECT 'National Football League', 'nfl.com'
    UNION ALL SELECT 'National Geographic en Español', 'ngenespanol.com'
    UNION ALL SELECT 'National Hockey League', 'nhl.com'
    UNION ALL SELECT 'Nice News', 'nicenews.com'
    UNION ALL SELECT 'Nieman Journalism Lab', 'niemanlab.org'
    UNION ALL SELECT 'Nintendo Life', 'nintendolife.com'
    UNION ALL SELECT 'Nir Eyal', 'nirandfar.com'
    UNION ALL SELECT 'NJ.com', 'nj.com'
    UNION ALL SELECT 'NME', 'nme.com'
    UNION ALL SELECT 'Noema Magazine', 'noemamag.com'
    UNION ALL SELECT 'No Film School', 'nofilmschool.com'
    UNION ALL SELECT 'Le Nouvel Obs', 'nouvelobs.com'
    UNION ALL SELECT 'Nss Magazine', 'nssmag.com'
    UNION ALL SELECT 'Eater', 'ny.eater.com'
    UNION ALL SELECT 'NYLON', 'nylon.com'
    UNION ALL SELECT 'ÖKOTEST', 'oekotest.de'
    UNION ALL SELECT 'Nick Maggiulli', 'ofdollarsanddata.com'
    UNION ALL SELECT 'OkayAfrica', 'okayafrica.com'
    UNION ALL SELECT 'Okayplayer', 'okayplayer.com'
    UNION ALL SELECT 'Olive', 'olivemagazine.com'
    UNION ALL SELECT 'Onda Cero', 'ondacero.es'
    UNION ALL SELECT 'The One Percent Rule', 'onepercentrule.substack.com'
    UNION ALL SELECT 'Open', 'open.online'
    UNION ALL SELECT 'ORF.at', 'orf.at'
    UNION ALL SELECT 'Outdoor Life', 'outdoorlife.com'
    UNION ALL SELECT 'Outlook India', 'outlookindia.com'
    UNION ALL SELECT 'OZY', 'ozy.com'
    UNION ALL SELECT 'Parents', 'parents.com'
    UNION ALL SELECT 'Paris Match', 'parismatch.com'
    UNION ALL SELECT 'PC-WELT', 'pcwelt.de'
    UNION ALL SELECT 'PFF', 'pff.com'
    UNION ALL SELECT 'philosophie Magazin', 'philomag.de'
    UNION ALL SELECT 'Phonandroid', 'phonandroid.com'
    UNION ALL SELECT 'PopCrush', 'popcrush.com'
    UNION ALL SELECT 'Popula', 'popula.com'
    UNION ALL SELECT 'The Post and Courier', 'postandcourier.com'
    UNION ALL SELECT 'profil', 'profil.at'
    UNION ALL SELECT 'PFSN', 'profootballnetwork.com'
    UNION ALL SELECT 'Pro Football Rumors', 'profootballrumors.com'
    UNION ALL SELECT 'Pro Hockey Rumors', 'prohockeyrumors.com'
    UNION ALL SELECT 'Protean Magazine', 'proteanmag.com'
    UNION ALL SELECT 'Pacific Standard', 'psmag.com'
    UNION ALL SELECT 'Psyche', 'psyche.co'
    UNION ALL SELECT 'Psychologie Heute', 'psychologie-heute.de'
    UNION ALL SELECT 'Psychologie-Magazin', 'psymag.de'
    UNION ALL SELECT 'Público', 'publico.es'
    UNION ALL SELECT 'Punch', 'punchdrink.com'
    UNION ALL SELECT 'Quarks', 'quarks.de'
    UNION ALL SELECT 'Qué!', 'que.es'
    UNION ALL SELECT 'Queer.de', 'queer.de'
    UNION ALL SELECT 'Radio France', 'radiofrance.fr'
    UNION ALL SELECT 'RaiNews', 'rainews.it'
    UNION ALL SELECT 'rbb24', 'rbb24.de'
    UNION ALL SELECT 'RealGM', 'realgm.com'
    UNION ALL SELECT 'Real Simple', 'realsimple.com'
    UNION ALL SELECT 'Redattore Sociale', 'redattoresociale.it'
    UNION ALL SELECT 'reisereporter', 'reisereporter.de'
    UNION ALL SELECT 'Relevo', 'relevo.com'
    UNION ALL SELECT 'renk.', 'renk-magazin.de'
    UNION ALL SELECT 'REPUBLIK', 'republik.ch'
    UNION ALL SELECT 'Rest of World', 'restofworld.org'
    UNION ALL SELECT 'Review Geek', 'reviewgeek.com'
    UNION ALL SELECT 'AD', 'revistaad.es'
    UNION ALL SELECT 'GQ', 'revistagq.com'
    UNION ALL SELECT 'Vanity Fair', 'revistavanityfair.es'
    UNION ALL SELECT 'Rewind Zone', 'rewindzone.com'
    UNION ALL SELECT 'RiffReporter', 'riffreporter.de'
    UNION ALL SELECT 'Rivista Studio', 'rivistastudio.com'
    UNION ALL SELECT 'Rivista Undici', 'rivistaundici.com'
    UNION ALL SELECT 'RND', 'rnd.de'
    UNION ALL SELECT 'Roger Ebert', 'rogerebert.com'
    UNION ALL SELECT 'Rolling Stone', 'rollingstone.de'
    UNION ALL SELECT 'Rolling Stone', 'rollingstone.it'
    UNION ALL SELECT 'Romper', 'romper.com'
    UNION ALL SELECT 'Rheinische Post', 'rp-online.de'
    UNION ALL SELECT 'RTBF', 'rtbf.be'
    UNION ALL SELECT 'RTÉ', 'rte.ie'
    UNION ALL SELECT 'Ryan Holiday', 'ryanholiday.net'
    UNION ALL SELECT 'Sain et Naturel', 'sain-et-naturel.ouest-france.fr'
    UNION ALL SELECT 'The San Diego Union-Tribune', 'sandiegouniontribune.com'
    UNION ALL SELECT 'SAPIENS', 'sapiens.org'
    UNION ALL SELECT 'Saveur', 'saveur.com'
    UNION ALL SELECT 'SBI Soccer', 'sbisoccer.com'
    UNION ALL SELECT 'ORF.at', 'science.orf.at'
    UNION ALL SELECT 'Science Focus', 'sciencefocus.com'
    UNION ALL SELECT 'Distillations', 'sciencehistory.org'
    UNION ALL SELECT 'Science News', 'sciencenews.org'
    UNION ALL SELECT 'Science Notes', 'sciencenotes.de'
    UNION ALL SELECT 'Sciences et Avenir', 'sciencesetavenir.fr'
    UNION ALL SELECT 'Scinexx', 'scinexx.de'
    UNION ALL SELECT 'ScreenCrush', 'screencrush.com'
    UNION ALL SELECT 'Scroll.in', 'scroll.in'
    UNION ALL SELECT 'SELF', 'self.com'
    UNION ALL SELECT 'Semafor', 'semafor.com'
    UNION ALL SELECT 'SerPadres', 'serpadres.es'
    UNION ALL SELECT 'ABC.es', 'sevilla.abc.es'
    UNION ALL SELECT 'San Francisco Chronicle', 'sfchronicle.com'
    UNION ALL SELECT 'SheKnows', 'sheknows.com'
    UNION ALL SELECT 'Siamomine', 'siamomine.com'
    UNION ALL SELECT 'Sky Sports', 'skysports.com'
    UNION ALL SELECT 'SLAM', 'slamonline.com'
    UNION ALL SELECT 'smitten kitchen', 'smittenkitchen.com'
    UNION ALL SELECT 'SoraNews24', 'soranews24.com'
    UNION ALL SELECT 'Space.com', 'space.com'
    UNION ALL SELECT 'SpazioGames.it', 'spaziogames.it'
    UNION ALL SELECT 'The Spectator', 'spectator.co.uk'
    UNION ALL SELECT 'IEEE', 'spectrum.ieee.org'
    UNION ALL SELECT 'Spin', 'spin.com'
    UNION ALL SELECT 'Splendido Magazin', 'splendido-magazin.de'
    UNION ALL SELECT 'SpoilerTV', 'spoilertv.com'
    UNION ALL SELECT 'The Spokesman-Review', 'spokesman.com'
    UNION ALL SELECT 'Diario SPORT', 'sport.es'
    UNION ALL SELECT 'Sky Sport', 'sport.sky.it'
    UNION ALL SELECT 'Sportico', 'sportico.com'
    UNION ALL SELECT 'Sporting News', 'sportingnews.com'
    UNION ALL SELECT 'sportschau', 'sportschau.de'
    UNION ALL SELECT 'Sportsnet', 'sportsnet.ca'
    UNION ALL SELECT 'Squirrel News', 'squirrel-news.net'
    UNION ALL SELECT 'SRF', 'srf.ch'
    UNION ALL SELECT 'stern', 'stern.de'
    UNION ALL SELECT 'Stylist', 'stylist.co.uk'
    UNION ALL SELECT 'SuperHeroHype', 'superherohype.com'
    UNION ALL SELECT 'SWR', 'swr.de'
    UNION ALL SELECT 'SWR3', 'swr3.de'
    UNION ALL SELECT 'SWR', 'swrfernsehen.de'
    UNION ALL SELECT 'SYFY WIRE', 'syfy.com'
    UNION ALL SELECT 'SZ Magazin', 'sz-magazin.sueddeutsche.de'
    UNION ALL SELECT 't-online', 't-online.de'
    UNION ALL SELECT 'Tablet Magazine', 'tabletmag.com'
    UNION ALL SELECT 'tag eins Magazin', 'tageins.at'
    UNION ALL SELECT 'Tages-Anzeiger', 'tagesanzeiger.ch'
    UNION ALL SELECT 'talkSPORT', 'talksport.com'
    UNION ALL SELECT 'Tampa Bay Times', 'tampabay.com'
    UNION ALL SELECT 'Task & Purpose', 'taskandpurpose.com'
    UNION ALL SELECT 'TASTE', 'tastecooking.com'
    UNION ALL SELECT 'Taste of Home', 'tasteofhome.com'
    UNION ALL SELECT 'Tasty', 'tasty.co'
    UNION ALL SELECT 'Everyeye', 'tech.everyeye.it'
    UNION ALL SELECT 'MIT Technology Review', 'technologyreview.es'
    UNION ALL SELECT 'Teen Vogue', 'teenvogue.com'
    UNION ALL SELECT 'Télérama', 'telerama.fr'
    UNION ALL SELECT 'Telva', 'telva.com'
    UNION ALL SELECT 'Stiftung Warentest', 'test.de'
    UNION ALL SELECT 'Texas Observer', 'texasobserver.org'
    UNION ALL SELECT 'Sky TG24', 'tg24.sky.it'
    UNION ALL SELECT 'the decoder', 'the-decoder.de'
    UNION ALL SELECT 'The Fence', 'the-fence.com'
    UNION ALL SELECT 'The Independent', 'the-independent.com'
    UNION ALL SELECT 'The American Scholar', 'theamericanscholar.org'
    UNION ALL SELECT 'The Blast', 'theblast.com'
    UNION ALL SELECT 'The Diplomat', 'thediplomat.com'
    UNION ALL SELECT 'The Drive', 'thedrive.com'
    UNION ALL SELECT 'The Face', 'theface.com'
    UNION ALL SELECT 'The Fader', 'thefader.com'
    UNION ALL SELECT 'The Hockey Writers', 'thehockeywriters.com'
    UNION ALL SELECT 'The Hustle', 'thehustle.co'
    UNION ALL SELECT 'them', 'them.us'
    UNION ALL SELECT 'The Marginalian', 'themarginalian.org'
    UNION ALL SELECT 'The Markup', 'themarkup.org'
    UNION ALL SELECT 'The Marshall Project', 'themarshallproject.org'
    UNION ALL SELECT 'The Muse', 'themuse.com'
    UNION ALL SELECT 'The Narwhal', 'thenarwhal.ca'
    UNION ALL SELECT 'The Objective', 'theobjective.com'
    UNION ALL SELECT 'The Quietus', 'thequietus.com'
    UNION ALL SELECT 'MIT Press Reader', 'thereader.mitpress.mit.edu'
    UNION ALL SELECT 'The Score', 'thescore.com'
    UNION ALL SELECT 'The Spruce', 'thespruce.com'
    UNION ALL SELECT 'The Stranger', 'thestranger.com'
    UNION ALL SELECT 'TheStreet', 'thestreet.com'
    UNION ALL SELECT 'The Week', 'theweek.in'
    UNION ALL SELECT 'TheWrap', 'thewrap.com'
    UNION ALL SELECT 'The Zoe Report', 'thezoereport.com'
    UNION ALL SELECT 'ThoughtCo', 'thoughtco.com'
    UNION ALL SELECT 'Tim Ferriss', 'tim.blog'
    UNION ALL SELECT 'Time Out', 'timeout.com'
    UNION ALL SELECT 'Times Now', 'timesnownews.com'
    UNION ALL SELECT 'Tim Harford', 'timharford.com'
    UNION ALL SELECT 'Today Show', 'today.com'
    UNION ALL SELECT 'Top Gear', 'topgear.es'
    UNION ALL SELECT 'Topic', 'topic.com'
    UNION ALL SELECT 'Tor.com', 'tor.com'
    UNION ALL SELECT 'Condé Nast Traveler', 'traveler.es'
    UNION ALL SELECT 'Tribune India', 'tribuneindia.com'
    UNION ALL SELECT 'TV Fanatic', 'tvfanatic.com'
    UNION ALL SELECT 'TVLine.com', 'tvline.com'
    UNION ALL SELECT 'TV Series Finale', 'tvseriesfinale.com'
    UNION ALL SELECT 'TV Shows Ace', 'tvshowsace.com'
    UNION ALL SELECT 'TV Tonight', 'tvtonight.com.au'
    UNION ALL SELECT 'Übermedien', 'uebermedien.de'
    UNION ALL SELECT 'Ultimate Classic Rock', 'ultimateclassicrock.com'
    UNION ALL SELECT 'Undark', 'undark.org'
    UNION ALL SELECT 'Usbek & Rica', 'usbeketrica.com'
    UNION ALL SELECT 'Us Weekly', 'usmagazine.com'
    UNION ALL SELECT 'U.S. News & World Report', 'usnews.com'
    UNION ALL SELECT 'Utopia', 'utopia.de'
    UNION ALL SELECT 'UX Planet', 'uxplanet.org'
    UNION ALL SELECT 'Valigia Blu', 'valigiablu.it'
    UNION ALL SELECT 'El Español', 'vandal.elespanol.com'
    UNION ALL SELECT 'Vanity Fair', 'vanityfair.fr'
    UNION ALL SELECT 'Vanity Fair', 'vanityfair.it'
    UNION ALL SELECT 'Verfassungsblog', 'verfassungsblog.de'
    UNION ALL SELECT 'Veto Magazin', 'veto-mag.de'
    UNION ALL SELECT 'Viajes National Geographic', 'viajes.nationalgeographic.com.es'
    UNION ALL SELECT 'Vida Extra', 'vidaextra.com'
    UNION ALL SELECT 'VGC', 'videogameschronicle.com'
    UNION ALL SELECT 'Village Voice', 'villagevoice.com'
    UNION ALL SELECT 'VITA', 'vita.it'
    UNION ALL SELECT 'Voice of America', 'voanews.com'
    UNION ALL SELECT 'VOGUE', 'vogue.de'
    UNION ALL SELECT 'Vogue', 'vogue.es'
    UNION ALL SELECT 'Vogue India', 'vogue.in'
    UNION ALL SELECT 'Vogue', 'vogue.it'
    UNION ALL SELECT 'Washingtonian', 'washingtonian.com'
    UNION ALL SELECT 'Washington Monthly', 'washingtonmonthly.com'
    UNION ALL SELECT 'watson CH', 'watson.ch'
    UNION ALL SELECT 'watson', 'watson.de'
    UNION ALL SELECT 'WAZ', 'waz.de'
    UNION ALL SELECT 'WEB.DE', 'web.de'
    UNION ALL SELECT 'Well+Good', 'wellandgood.com'
    UNION ALL SELECT 'Wiener Zeitung', 'wienerzeitung.at'
    UNION ALL SELECT 'Wired', 'wired.it'
    UNION ALL SELECT 'WirtschaftsWoche', 'wiwo.de'
    UNION ALL SELECT 'W Magazine', 'wmagazine.com'
    UNION ALL SELECT 'wmn.', 'wmn.de'
    UNION ALL SELECT 'Word In Black', 'wordinblack.com'
    UNION ALL SELECT 'WWWhatsnew', 'wwwhatsnew.com'
    UNION ALL SELECT 'X', 'x.com'
    UNION ALL SELECT 'Xataka Android', 'xatakandroid.com'
    UNION ALL SELECT 'Yardbarker', 'yardbarker.com'
    UNION ALL SELECT 'YourStory', 'yourstory.com'
    UNION ALL SELECT 'Youtube', 'youtu.be'
    UNION ALL SELECT 'ZDF', 'zdf.de'
    UNION ALL SELECT 'ZDFheute', 'zdfheute.de'
    UNION ALL SELECT 'ZEITjUNG', 'zeitjung.de'
    UNION ALL SELECT 'Zócalo Public Square', 'zocalopublicsquare.org'
    UNION ALL SELECT 'Zucker & Jagdwurst', 'zuckerjagdwurst.com'
) AS dbm
ORDER BY dbm.domain_name;
